# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions
jspack( )
 {
   /usr/local/bin/jsPacker.pl -i $1.unpack.js -o $1.js -s
 }

rgrep( )
 {
   repo grep $1
 }

changePrompt( )
{
  DIR=$(pwd)
  ME=$(whoami)

  if [[ $DIR == *$ME* ]]
  then
    export PS1="\e[0;0m[\u@\h \W]\$ \e[m";
  else
    export PS1="\e[0;31m[\u@\h \W]\$ \e[m";
  fi
}

#function cd ( )
#{
#  builtin cd "$@" && changePrompt;
#}
